modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="largemeals"
version="${file.jarVersion}"
displayName="Large Meals"
logoFile="logo.png"
credits="jamb, NEWW0RID, ChirenCQR, Khanh Nguyen"
authors="FoundWiz"
description='''
This Farmer's Delight addon adds some recipes to the main mod.
'''
[[dependencies.largemeals]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.largemeals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.largemeals]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.2.0,)"
ordering = "AFTER"
side = "BOTH"